# Generated by Django 3.2.5 on 2021-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipage',
            old_name='versions',
            new_name='all_versions',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='active_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Поточна версія'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='current_version',
            field=models.PositiveIntegerField(verbose_name='Остання версія'),
        ),
    ]
